### ISSUE TITLE
CheatBreaker 1.8.9 won't start me

### ISSUE THREAD

**Issue by ByRafusius** [ShonP40/Offline-CheatBreaker#11]
Once I start the cheatbreaker in the stable launcher. When starting version 1.8.9 it starts well and while it is on the loading screen that says "Mojang" it tells me that the game does not respond and closes and returns me to the launcher, which does not happen when entering 1.7.10 already that I can play perfectly there. What could I do? I want to use 1.8.9, since I own a network which is from 1.8.9 onwards and does not support 1.7.10. I would appreciate any kind of response.

PD: Sorry if my English is a bad thing, but I speak Spanish and I am using the translator to communicate: /

**Comment by ShonP40** [comment]
I’d suggest launching normal 1.8 and disabling all your shader/texture packs and then trying to launch 1.8 Offline CheatBreaker again.
