### ISSUE TITLE
Não consigo deixar o meu cheatbreaker online oque eu faço?

### ISSUE THREAD

**Issue by raffau18** [ShonP40/Offline-CheatBreaker#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. `macOS 10.13`]
 - Game version [e.g. `1.7.10`]
 - Game build number [e.g. `1m2c771`]
 - Launcher type [e.g. `Beta`]
 - Launcher version [e.g. `2.0.0 Beta 5`]
 - If on **Linux**, provide the output of `java -version`

**Additional context**

**Comment by ShonP40** [comment]
Closing this issue for the following reasons:

1. Every issue created has to be in English.
2. Not enough info was provided.
