### ISSUE TITLE
Ran installer, launcher isnt showing up (Linux)

### ISSUE THREAD

**Issue by Graham-Hart** [ShonP40/Offline-CheatBreaker#3]

**Comment by ShonP40** [comment]
We don't have an installer for Linux
You just run the jar file.

Make sure that you have Java 8 64-bit installed.
If you don't have it, you can follow my guide here: https://github.com/ShonP40/Java-installation-instructions-for-Ubuntu

**Comment by ShonP40** [comment]
Closed for inactivity

**Comment by ShonP40** [comment]
Closed for inactivity
