### ISSUE TITLE
Linux cb offline doesnt`t work(Ubuntu 20.04)

### ISSUE THREAD

**Issue by DedSec-F0x** [ShonP40/Offline-CheatBreaker#6]
when i run the cb its gives a error: Exception in thread "Client thread" java.lang.NullPointerException and 'Unknow Source", how to solve this problem ? (i have installed java)

**Comment by ShonP40** [comment]
Are you sure that you have normal Java installed? (not OpenJDK).

Open Terminal and run `java -version`

**Comment by DedSec-F0x** [comment]
> Are you sure that you have normal Java installed? (not OpenJDK).
> 
> Open Terminal and run `java -version`

i fixed! thank you so much
